import pandas as pd
adjs = ['adaptable',
        'ambitious',
        'approachable',
        'competitive',
        'confident',
        'customer-focused',
        'devoted',
        'educated',
        'efficient',
        'fast-paced',
        'flexible',
        'focused',
        'honest',
        'independent',
        'inquisitive',
        'insightful',
        'open-minded',
        'organized',
        'personable',
        'productive',
        'qualified',
        'relaxed',
        'resourceful',
        'responsible',
        'technological',
        'adept',
        'alluring',
        'ample',
        'bountiful',
        'brave',
        'breathtaking',
        'brilliant',
        'capable',
        'considerate',
        'courageous',
        'dazzling',
        'elegant',
        'enchanting',
        'faithful',
        'fearless',
        'frank',
        'gleaming',
        'glimmering',
        'glistening',
        'glittering',
        'glowing',
        'humorous',
        'knowledgeable',
        'lovely',
        'loving',
        'lustrous',
        'magnificent',
        'marvelous',
        'nice',
        'optimistic',
        'passionate',
        'persistent',
        'plucky',
        'proficient',
        'ravishing',
        'romantic',
        'self-confident',
        'sensible',
        'sleek',
        'sparkling',
        'thoughtful',
        'twinkling',
        'vivid',
        'vibrant',
        'vivacious',
        'warm-hearted',
        'willing',
        'zestful']
usernames = ['Lion',
             'Tiger',
             'Goat',
             'Horse',
             'Donkey',
             'Dog',
             'Cat',
             'Pig',
             'Panther',
             'Leopard',
             'Cheetah',
             'Cow',
             'Walrus',
             'Otter',
             'Giraffe',
             'Sheep',
             'Rabbit',
             'Monkey',
             'Flamingo',
             'Crow',
             'Hen',
             'Vulture',
             'Eagle',
             'Peacock',
             'Pigeon',
             'Emu',
             'Ostrich',
             'Dove',
             'Stork']

import random

def random_name():
    have_username = False
    name = ''
    while not have_username:
        random_adj = random.sample(adjs, 1)[0]
        username_adj = random.sample(usernames, 1)[0]
        name = f'{random_adj} {username_adj}'
        have_username = True
    return name.title()